name: Generate AAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Clean setup forcing Gradle 9.0 without old cache interference
    - name: Setup and Run Gradle Build
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '9.0.0'
        cache-disabled: true # Forces a clean evaluation phase
        arguments: :animator:assembleRelease --no-daemon
